version: '3.8'

services:
  flood-watch-web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    restart: unless-stopped
    environment:
      - NGINX_HOST=flood-watch.local
      - NGINX_PORT=80